@startuml data_persistance
title Data persistance

class Player(Dataclass){ 
    pk : int
    chess_id : str
    last_name : str
    first_name : str
    birthdate : date    
}

class Score(Dataclass){
    player_pk : int
    score : float
}

class Match(Dataclass){
    pk : int
    player_a : int
    player_b : int
    scores : tuple(Score, Score)
}

class Turn(Dataclass) {
    pk : int
    name : str
    start_datetime : datetime
    end_datetime : datetime
    matches : list[Match]
}

class Tournament(Dataclass){
    pk : int
    name : str
    place : str
    start_date : date
    end_date : str    
    description : str      
    turn_count : int
    turns : list[Turn]
    players : list[Players]
}

class DataHandler(Generic[Dataclass]){
    write_data_to_file()->Result
    read_data_from_file()->str
    convert_to_dataclass()->Dataclass
    serialize_dataclass->str
}
@enduml
