@startuml menus
title Menus

class MenuItem{
    name : str
    shortcut : str

    run_item() -> Result
}

class Menu{
    title : str
    menu_items : list[MenuItem]

    run_menu_item(shortcut : str) -> Result
}

class MenuRenderer{

}

@enduml