@startuml player_architecture
title Player Workflow

hide footbox

autonumber

box "View" #DBEAFE
    boundary View
    
end box

box "Controller" #DCFCE7
control PromptHandler
    control RenderHandler
    control ActionRunner
    control PlayerController
    
end box

box "Data" #FEF3C7
    control PlayerService
    database DataBase
end box



group Waiting for user input
    PlayerController -> ActionRunner : action_runner.run()
    ActionRunner -> PromptHandler : prompt_handler.prompt_action()
    PromptHandler -> View : view.prompt_action()
end 

group Recieve user input
    View --> PromptHandler : return prompt_action()
    PromptHandler -> PromptHandler : validator.validate_action_input()
    PromptHandler --> PlayerController : return action
end

group Input treatment
    group Getting data
        PlayerController -> PlayerService : action()
        PlayerService -> DataBase : get_data()
        DataBase --> PlayerService : return json_data
        PlayerService -> PlayerService : json_data to player_models
        PlayerService --> PlayerController : return player_models
        PlayerController -> RenderHandler  : renderer_handler.render_models(player_models)  
        RenderHandler -> View : view.render_models(player_models)
    end

    group writing data
        PlayerController -> PlayerService : save_new_player(data_input)
        PlayerService -> PlayerService : data_input to player_model
        PlayerService -> DataBase : player_model to json
    end
end


group Looping
    ActionRunner -> ActionRunner : while MenuState.continue_loop()
end




@endumld